/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { useFrame } from '@react-three/fiber'

export function Model(props) {
  const { nodes, materials } = useGLTF("/Three_13.glb");
    const myMesh = useRef();
  
    useFrame(() => {
        // myMesh.current.rotation.x += 0.005
        myMesh.current.rotation.z += 0.02
      })


  return (
    <group {...props} dispose={null}>
      <mesh
      ref={myMesh}
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.001"]}
        scale={[8, 8, 8]}
        rotation={[-Math.PI / 2.2, 3.14, 3.2]}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Three_13.glb");

